version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=carbon_counter_db
    ports:
      - "5433:5432"

  backend:
    build: ./backend
    volumes:
      - ./backend/app:/app/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=carbon_counter_db
      - POSTGRES_SERVER=db # Use the service name 'db' to connect
      - POSTGRES_PORT=5432 # Inside the docker network, it's the default port
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
