# docker-compose.yml
# --- MODIFIED FILE ---
# We are adding a command to the backend service to wait for the DB.

version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=carbon_counter_db
    ports:
      - "5433:5432"

  backend:
    build: ./backend
    volumes:
      - ./backend/app:/app/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=carbon_counter_db
      - POSTGRES_SERVER=db 
      - POSTGRES_PORT=5432
    depends_on:
      - db
    command: >
      sh -c "python app/db/wait_for_db.py &&
         python -m app.db.create_tables &&
         gunicorn -k uvicorn.workers.UvicornWorker -w 4 -b 0.0.0.0:8000 app.main:app"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data: