services:
  # 1. The PostgreSQL Database
  - type: pserv
    name: carbon-counter-db
    plan: free
    postgres:
      databaseName: carbon_counter_db
      user: postgres
      majorVersion: 14

  # 2. The FastAPI Backend
  - type: web
    name: carbon-counter-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: carbon-counter-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

  # 3. The React Frontend
  - type: static site
    name: carbon-counter-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: carbon-counter-backend
          property: url
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
