# This top-level key is for defining databases.
databases:
  - name: carbon-counter-db
    databaseName: carbon_counter_db
    user: postgres
    plan: free

# This top-level key is for web services and background workers.
services:
  # 1. The FastAPI Backend
  - type: web
    name: carbon-counter-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      # This correctly references the database defined in the 'databases' section
      - key: DATABASE_URL
        fromDatabase:
          name: carbon-counter-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

# This top-level key is specifically for static sites.
staticSites:
  # 2. The React Frontend
  - name: carbon-counter-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: carbon-counter-backend
          property: url
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
